/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qpatient_sender;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qpatient_sender extends AbstractQpatient_sender { 
	
	public Qpatient_sender(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
		System.out.println("PAZIENTE NOME DELL'ATTORE: " + actorId);
		System.out.println("PAZIENTE CONTESTO DELL'ATTORE: " + myCtx.getName());
	}
	
	public String getId(final String oldID) {
		String newID = oldID.substring(0, oldID.length()-5);
		String ID = newID.replaceAll("\\D+", ""); 
//		System.out.println("IL NUMERO DEL MIO QACTOR è: " + ID);
		return ID;
	}
	
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
