/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qpatient_sensor_manager;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.QActorMessage;
import it.unibo.qactors.QActorUtils;

public class Qpatient_sensor_manager extends AbstractQpatient_sensor_manager { 
	public Qpatient_sensor_manager(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	public void print(String str) {
		String idActor = this.getId(this.getName());
		QActorMessage mqa;
		try {
			mqa = QActorUtils.buildMsg(myCtx, this.getName(), "print_patient_gui", "qpatient_gui_manager"+ idActor, "dispatch", "print_patient_gui('"+str+"')");
			this.sendMsg(mqa.msgId(), mqa.msgReceiver(), mqa.msgType(), mqa.msgContent());
		} catch (Exception e) {
			e.printStackTrace();
		}
//		gui.printOnGUI(str);
	}
	
	public String getId(final String oldID) {
		String newID = oldID.substring(0, oldID.length()-5);
		String ID = newID.replaceAll("\\D+", "");
		return ID;
	}
}
