/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qpatient_notification_receiver;
import java.awt.Color;

import it.unibo.baseEnv.basicFrame.EnvFrame;
import it.unibo.is.interfaces.IBasicEnvAwt;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qdoctor_notification_receiver.CustomGUIDoctorNotifReceiver;

public class Qpatient_notification_receiver extends AbstractQpatient_notification_receiver { 
	
	private CustomGUIPatientNotifReceiver gui;

	public Qpatient_notification_receiver(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
		System.out.println("PAZIENTE NOME DELL'ATTORE: " + actorId);
		System.out.println("PAZIENTE CONTESTO DELL'ATTORE: " + myCtx.getName());
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	
	protected void addInputPanel(int size) {}
	
	protected void addCmdPanel() {}
	
	public void print(String str) {
		gui.printOnGUI(str);
	}
	
	public void createGUI() {
		IBasicEnvAwt env = outEnvView.getEnv();
		if(env == null) {
			env = new EnvFrame("H2-Patient Notification Receiver", Color.green, Color.black);
			env.init();
			((EnvFrame)env).setSize(800,430);
		}
		env.writeOnStatusBar("H2-Patient Notification Receiver" + " | working ... ",14);
		gui = new CustomGUIPatientNotifReceiver(env,actorId,myCtx);
	}
}
