/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qdoctor_notification_sender;
import java.awt.Color;

import it.unibo.baseEnv.basicFrame.EnvFrame;
import it.unibo.is.interfaces.IBasicEnvAwt;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qdoctor_notification_sender extends AbstractQdoctor_notification_sender {
	
	private CustomGUISupportAdvice gui;
	
	public Qdoctor_notification_sender(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
		System.out.println("NOME DELL'ATTORE: " + actorId);
		System.out.println("CONTESTO DELL'ATTORE: " + myCtx.getName());
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	
	public String getId(final String oldID) {
		String newID = oldID.substring(0, oldID.length()-5);
		String ID = newID.replaceAll("\\D+", "");
		System.out.println("ID CHE PRENDO DALL'ATTORE DEL DOTTORE " + ID);
		return ID;
	}

	protected void addInputPanel(int size) {}
	
	protected void addCmdPanel() {}
	
	public void print(String str) {
		gui.printOnGUI(str);
	}
	
	public void createGUI() {
		IBasicEnvAwt env = outEnvView.getEnv();
		if(env == null) {
			env = new EnvFrame("H2-advice", Color.white, Color.black);
			env.init();
			((EnvFrame)env).setSize(800,430);
		}
		env.writeOnStatusBar("H2-advice" + " | working ... ",14);
		gui = new CustomGUISupportAdvice(env,myCtx,this);
	}
	
}
