/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qdoctor_data_retriever;
import java.awt.Color;

import it.unibo.baseEnv.basicFrame.EnvFrame;
import it.unibo.is.interfaces.IBasicEnvAwt;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qdoctor_data_retriever.CustomGUIDoctorDataRetriever;

public class Qdoctor_data_retriever extends AbstractQdoctor_data_retriever { 
	
	private CustomGUIDoctorDataRetriever gui;
	
	public Qdoctor_data_retriever(String actorId, QActorContext myCtx, IOutputEnvView outEnvView)  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	
	public String getId(final String oldID) {
		String newID = oldID.substring(0, oldID.length()-5);
		String ID = newID.replaceAll("\\D+", "");
		return ID;
	}
	
	protected void addInputPanel(int size) {}
	
	protected void addCmdPanel() {}
	
	public void print(String str) {
		gui.printOnGUI(str);
	}
	
	public void createGUI() {
		IBasicEnvAwt env = outEnvView.getEnv();
		if(env == null) {
			env = new EnvFrame("H2 - Doctor Data Retriever", Color.white, Color.black);
			env.init();
			((EnvFrame)env).setSize(800,430);
		}
		env.writeOnStatusBar("H2 - Doctor Data Retriever" + " | working ... ",14);
		gui = new CustomGUIDoctorDataRetriever(env,myCtx,this,this.getId(this.getName()));
}
}
