/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qdc_register;
import java.awt.Color;

import it.unibo.baseEnv.basicFrame.EnvFrame;
import it.unibo.is.interfaces.IBasicEnvAwt;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qdc_register.CustomGUIRegistration;

public class Qdc_register extends AbstractQdc_register { 
	
	private CustomGUIRegistration gui;
	
	public Qdc_register(String actorId, QActorContext myCtx, IOutputEnvView outEnvView)  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	
	protected void addInputPanel(int size) {}
	
	protected void addCmdPanel() {}
	
	public void print(String str) {
		gui.printOnGUI(str);
	}
	
	public void createGUI() {
		IBasicEnvAwt env = outEnvView.getEnv();
		if(env == null) {
			env = new EnvFrame("H2-Registration", Color.yellow, Color.black);
			env.init();
			((EnvFrame)env).setSize(800,430);
		}
		env.writeOnStatusBar("H2-Registration" + " | working ... ",14);
		gui = new CustomGUIRegistration(env,myCtx,this);
	}
}
